[project]
name = "tp2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=5.0.0",
    "deepeval==3.9.9",
    "matplotlib>=3.10.9",
    "pandas>=3.0.3",
    "sqlparse>=0.5.5",
    "transformers>=5.10.2",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]
